<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://riipl.wfubmc.edu/riiplqa" xmlns:riiplqa="http://riipl.wfubmc.edu/riiplqa" xmlns:xnat="http://nrg.wustl.edu/xnat" xmlns:xdat="http://nrg.wustl.edu/xdat" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:import namespace="http://nrg.wustl.edu/xnat" schemaLocation="../xnat/xnat.xsd"/>
	
	<xs:element name="SegCat12"	type="riiplqa:SegCat12Data"/>
	
	<xs:complexType name="SegCat12Data">
		<xs:complexContent>
			<xs:extension base="xnat:mrAssessorData">
				<xs:annotation>
					<xs:documentation>CAT12 Segmentation Image QA Report</xs:documentation>
				</xs:annotation>
				<xs:sequence minOccurs="0">
					<xs:element name="subject" type="xs:string" minOccurs="0"/>
					<xs:element name="qcSession" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType>
							<xs:sequence minOccurs="0">
								<xs:element name="imgData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="date" type="xs:date" use="required"/>
										<xs:attribute name="time" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="tisData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence minOccurs="0">
											<xs:element name="tissue" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="gm" type="xs:float"/>
													<xs:attribute name="wm" type="xs:float"/>
													<xs:attribute name="csf" type="xs:float"/>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="filedate" type="xs:date" use="required"/>
										<xs:attribute name="filetime" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="qcImage" type="xs:string" use="optional"/>
							<xs:attribute name="quality" type="xs:string" use="required"/>
							<xs:attribute name="username" type="xs:string" use="required"/>
							<xs:attribute name="date" type="xs:date" use="required"/>
							<xs:attribute name="time" type="xs:time" use="required"/>
							<xs:attribute name="comments" type="xs:string"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>	
</xs:schema>