<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://riipl.wfubmc.edu/riiplqa" xmlns:riiplqa="http://riipl.wfubmc.edu/riiplqa" xmlns:xnat="http://nrg.wustl.edu/xnat" xmlns:xdat="http://nrg.wustl.edu/xdat" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:import namespace="http://nrg.wustl.edu/xnat" schemaLocation="../xnat/xnat.xsd"/>
	
	<xs:element name="SegCat12"					type="riiplqa:SegCat12Data"/>
	<xs:element name="NormCat12PCASL8"			type="riiplqa:NormCat12PCASL8Data"/>
	<xs:element name="NormCat12PCASL"			type="riiplqa:NormCat12PCASLData"/>
	<xs:element name="NormCat12PCASLbh"         type="riiplqa:NormCat12PCASLbhData"/>
	<xs:element name="NormCat12FMRI"         	type="riiplqa:NormCat12FMRIData"/>
	<xs:element name="NormCat12DTI"             type="riiplqa:NormCat12DTIData"/>
	<xs:element name="NormCat12DKI"             type="riiplqa:NormCat12DKIData"/>
	<xs:element name="NormCat12NODDI"			type="riiplqa:NormCat12NODDIData"/>
	<xs:element name="NormCat12PETPVC"			type="riiplqa:NormCat12PETPVCData"/>
	
	<xs:complexType name="SegCat12Data">
		<xs:complexContent>
			<xs:extension base="xnat:mrAssessorData">
				<xs:annotation>
					<xs:documentation>CAT12 Segmentation Image QA Report</xs:documentation>
				</xs:annotation>
				<xs:sequence minOccurs="0">
					<xs:element name="subject" type="xs:string" minOccurs="0">
						<xs:annotation>
							<xs:appinfo>
								<xdat:field display="true"/>
							</xs:appinfo>
						</xs:annotation>
					</xs:element>
					<xs:element name="qcSession" minOccurs="0" >
						<xs:complexType>
							<xs:sequence minOccurs="0">
								<xs:element name="imgData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="date" type="xs:date" use="required"/>
										<xs:attribute name="time" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="tisData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence minOccurs="0">
											<xs:element name="tissue" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="gm" type="xs:float"/>
													<xs:attribute name="wm" type="xs:float"/>
													<xs:attribute name="csf" type="xs:float"/>
													<xs:attribute name="tiv" type="xs:float"/>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="filedate" type="xs:date" use="required"/>
										<xs:attribute name="filetime" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="qcImage" type="xs:string" use="optional"/>
							<xs:attribute name="quality" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="username" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="date" type="xs:date" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="time" type="xs:time" use="required"/>
							<xs:attribute name="comments" type="xs:string"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="NormCat12PCASL8Data">
		<xs:complexContent>
			<xs:extension base="xnat:mrAssessorData">
				<xs:annotation>
					<xs:documentation>CAT12 Normalization of 8 Phase PCASL QA Report</xs:documentation>
				</xs:annotation>
				<xs:sequence minOccurs="0">
					<xs:element name="subject" type="xs:string" minOccurs="0">
						<xs:annotation>
							<xs:appinfo>
								<xdat:field display="true"/>
							</xs:appinfo>
						</xs:annotation>
					</xs:element>
					<xs:element name="qcSession" minOccurs="0" >
						<xs:complexType>
							<xs:sequence minOccurs="0">
								<xs:element name="imgData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="date" type="xs:date" use="required"/>
										<xs:attribute name="time" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="tisData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence minOccurs="0">
											<xs:element name="tissue" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="imageFile" type="xs:string"/>
													<xs:attribute name="imageType" type="xs:string"/>
													<xs:attribute name="gm" type="xs:float"/>
													<xs:attribute name="wm" type="xs:float"/>
													<xs:attribute name="csf" type="xs:float"/>
													<xs:attribute name="gmThresh" type="xs:float"/>
													<xs:attribute name="wmThresh" type="xs:float"/>
													<xs:attribute name="csfThresh" type="xs:float"/>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="filedate" type="xs:date" use="required"/>
										<xs:attribute name="filetime" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="qcImage" type="xs:string" use="optional"/>
							<xs:attribute name="quality" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="username" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="date" type="xs:date" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="time" type="xs:time" use="required"/>
							<xs:attribute name="comments" type="xs:string" use="optional"/>
							<xs:attribute name="mvmtImage" type="xs:string" use="optional"/>
							<xs:attribute name="mvmtFile" type="xs:string" use="optional"/>
							<xs:attribute name="mvmtQuality" type="xs:string" use="optional"/>
							<xs:attribute name="mvmtDate" type="xs:date" use="optional"/>
							<xs:attribute name="mvmtTime" type="xs:time" use="optional"/>
							<xs:attribute name="mvmtMaxX" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxY" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxZ" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxPitch" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxRoll" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxYaw" type="xs:float" use="optional"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="NormCat12PCASLData">
		<xs:complexContent>
			<xs:extension base="xnat:mrAssessorData">
				<xs:annotation>
					<xs:documentation>CAT12 Normalization of PCASL QA Report</xs:documentation>
				</xs:annotation>
				<xs:sequence minOccurs="0">
					<xs:element name="subject" type="xs:string" minOccurs="0">
						<xs:annotation>
							<xs:appinfo>
								<xdat:field display="true"/>
							</xs:appinfo>
						</xs:annotation>
					</xs:element>
					<xs:element name="qcSession" minOccurs="0" >
						<xs:complexType>
							<xs:sequence minOccurs="0">
								<xs:element name="imgData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="date" type="xs:date" use="required"/>
										<xs:attribute name="time" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="tisData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence minOccurs="0">
											<xs:element name="tissue" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="imageFile" type="xs:string"/>
													<xs:attribute name="imageType" type="xs:string"/>
													<xs:attribute name="gm" type="xs:float"/>
													<xs:attribute name="wm" type="xs:float"/>
													<xs:attribute name="csf" type="xs:float"/>
													<xs:attribute name="gmThresh" type="xs:float"/>
													<xs:attribute name="wmThresh" type="xs:float"/>
													<xs:attribute name="csfThresh" type="xs:float"/>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="filedate" type="xs:date" use="required"/>
										<xs:attribute name="filetime" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="qcImage" type="xs:string" use="optional"/>
							<xs:attribute name="quality" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="username" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="date" type="xs:date" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="time" type="xs:time" use="required"/>
							<xs:attribute name="comments" type="xs:string" use="optional"/>
							<xs:attribute name="mvmtImage" type="xs:string" use="optional"/>
							<xs:attribute name="mvmtFile" type="xs:string" use="optional"/>
							<xs:attribute name="mvmtQuality" type="xs:string" use="optional"/>
							<xs:attribute name="mvmtDate" type="xs:date" use="optional"/>
							<xs:attribute name="mvmtTime" type="xs:time" use="optional"/>
							<xs:attribute name="mvmtMaxX" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxY" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxZ" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxPitch" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxRoll" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxYaw" type="xs:float" use="optional"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="NormCat12PCASLbhData">
		<xs:complexContent>
			<xs:extension base="xnat:mrAssessorData">
				<xs:annotation>
					<xs:documentation>CAT12 Normalization of PCASL Breath Hold QA Report (non-PVC)</xs:documentation>
				</xs:annotation>
				<xs:sequence minOccurs="0">
					<xs:element name="subject" type="xs:string" minOccurs="0">
						<xs:annotation>
							<xs:appinfo>
								<xdat:field display="true"/>
							</xs:appinfo>
						</xs:annotation>
					</xs:element>
					<xs:element name="qcSession" minOccurs="0" >
						<xs:complexType>
							<xs:sequence minOccurs="0">
								<xs:element name="imgData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="date" type="xs:date" use="required"/>
										<xs:attribute name="time" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="tisData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence minOccurs="0">
											<xs:element name="tissue" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="imageFile" type="xs:string"/>
													<xs:attribute name="imageType" type="xs:string"/>
													<xs:attribute name="gm" type="xs:float"/>
													<xs:attribute name="wm" type="xs:float"/>
													<xs:attribute name="csf" type="xs:float"/>
													<xs:attribute name="gmThresh" type="xs:float"/>
													<xs:attribute name="wmThresh" type="xs:float"/>
													<xs:attribute name="csfThresh" type="xs:float"/>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="filedate" type="xs:date" use="required"/>
										<xs:attribute name="filetime" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="qcImage" type="xs:string" use="optional"/>
							<xs:attribute name="quality" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="username" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="date" type="xs:date" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="time" type="xs:time" use="required"/>
							<xs:attribute name="comments" use="optional" type="xs:string"/>
							<xs:attribute name="mvmtImage" type="xs:string" use="optional"/>
							<xs:attribute name="mvmtFile" type="xs:string" use="optional"/>
							<xs:attribute name="mvmtQuality" type="xs:string" use="optional"/>
							<xs:attribute name="mvmtDate" type="xs:date" use="optional"/>
							<xs:attribute name="mvmtTime" type="xs:time" use="optional"/>
							<xs:attribute name="mvmtMaxX" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxY" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxZ" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxPitch" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxRoll" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxYaw" type="xs:float" use="optional"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="NormCat12FMRIData">
		<xs:complexContent>
			<xs:extension base="xnat:mrAssessorData">
				<xs:annotation>
					<xs:documentation>CAT12 Normalization of fMRI Sequence QA Report</xs:documentation>
				</xs:annotation>
				<xs:sequence minOccurs="0">
					<xs:element name="subject" type="xs:string" minOccurs="0">
						<xs:annotation>
							<xs:appinfo>
								<xdat:field display="true"/>
							</xs:appinfo>
						</xs:annotation>
					</xs:element>
					<xs:element name="qcSession" minOccurs="0" >
						<xs:complexType>
							<xs:sequence minOccurs="0">
								<xs:element name="imgData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="date" type="xs:date" use="required"/>
										<xs:attribute name="time" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="tisData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence minOccurs="0">
											<xs:element name="tissue" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="imageFile" type="xs:string"/>
													<xs:attribute name="imageType" type="xs:string"/>
													<xs:attribute name="gm" type="xs:float"/>
													<xs:attribute name="wm" type="xs:float"/>
													<xs:attribute name="csf" type="xs:float"/>
													<xs:attribute name="gmThresh" type="xs:float"/>
													<xs:attribute name="wmThresh" type="xs:float"/>
													<xs:attribute name="csfThresh" type="xs:float"/>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="filedate" type="xs:date" use="required"/>
										<xs:attribute name="filetime" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="qcImage" type="xs:string" use="optional"/>
							<xs:attribute name="quality" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="username" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="date" type="xs:date" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="time" type="xs:time" use="required"/>
							<xs:attribute name="comments" type="xs:string" use="optional"/>
							<xs:attribute name="mvmtImage" type="xs:string" use="optional"/>
							<xs:attribute name="mvmtFile" type="xs:string" use="optional"/>
							<xs:attribute name="mvmtQuality" type="xs:string" use="optional"/>
							<xs:attribute name="mvmtDate" type="xs:date" use="optional"/>
							<xs:attribute name="mvmtTime" type="xs:time" use="optional"/>
							<xs:attribute name="mvmtMaxX" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxY" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxZ" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxPitch" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxRoll" type="xs:float" use="optional"/>
							<xs:attribute name="mvmtMaxYaw" type="xs:float" use="optional"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="NormCat12DTIData">
		<xs:complexContent>
			<xs:extension base="xnat:mrAssessorData">
				<xs:annotation>
					<xs:documentation>CAT12 Normalization of DTI QA Report</xs:documentation>
				</xs:annotation>
				<xs:sequence minOccurs="0">
					<xs:element name="subject" type="xs:string" minOccurs="0">
						<xs:annotation>
							<xs:appinfo>
								<xdat:field display="true"/>
							</xs:appinfo>
						</xs:annotation>
					</xs:element>
					<xs:element name="qcSession" minOccurs="0" >
						<xs:complexType>
							<xs:sequence minOccurs="0">
								<xs:element name="imgData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="date" type="xs:date" use="required"/>
										<xs:attribute name="time" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="tisData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence minOccurs="0">
											<xs:element name="tissue" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType> 
													<xs:attribute name="imageFile" type="xs:string"/>
													<xs:attribute name="imageType" type="xs:string"/>
													<xs:attribute name="gm" type="xs:float"/>
													<xs:attribute name="wm" type="xs:float"/>
													<xs:attribute name="csf" type="xs:float"/>
													<xs:attribute name="gmThresh" type="xs:float"/>
													<xs:attribute name="wmThresh" type="xs:float"/>
													<xs:attribute name="csfThresh" type="xs:float"/>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="filedate" type="xs:date" use="required"/>
										<xs:attribute name="filetime" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="qcImage" type="xs:string" use="optional"/>
							<xs:attribute name="quality" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="username" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="date" type="xs:date" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="time" type="xs:time" use="required"/>
							<xs:attribute name="comments" use="optional" type="xs:string"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="NormCat12DKIData">
		<xs:complexContent>
			<xs:extension base="xnat:mrAssessorData">
				<xs:annotation>
					<xs:documentation>CAT12 Normalization of DKI QA Report</xs:documentation>
				</xs:annotation>
				<xs:sequence minOccurs="0">
					<xs:element name="subject" type="xs:string" minOccurs="0">
						<xs:annotation>
							<xs:appinfo>
								<xdat:field display="true"/>
							</xs:appinfo>
						</xs:annotation>
					</xs:element>
					<xs:element name="qcSession" minOccurs="0" >
						<xs:complexType>
							<xs:sequence minOccurs="0">
								<xs:element name="imgData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="date" type="xs:date" use="required"/>
										<xs:attribute name="time" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="tisData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence minOccurs="0">
											<xs:element name="tissue" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType> 
													<xs:attribute name="imageFile" type="xs:string"/>
													<xs:attribute name="imageType" type="xs:string"/>
													<xs:attribute name="gm" type="xs:float"/>
													<xs:attribute name="wm" type="xs:float"/>
													<xs:attribute name="csf" type="xs:float"/>
													<xs:attribute name="gmThresh" type="xs:float"/>
													<xs:attribute name="wmThresh" type="xs:float"/>
													<xs:attribute name="csfThresh" type="xs:float"/>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="filedate" type="xs:date" use="required"/>
										<xs:attribute name="filetime" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="qcImage" type="xs:string" use="optional"/>
							<xs:attribute name="quality" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="username" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="date" type="xs:date" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="time" type="xs:time" use="required"/>
							<xs:attribute name="comments" use="optional" type="xs:string"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="NormCat12NODDIData">
		<xs:complexContent>
			<xs:extension base="xnat:mrAssessorData">
				<xs:annotation>
					<xs:documentation>CAT12 Normalization of NODDI QA Report</xs:documentation>
				</xs:annotation>
				<xs:sequence minOccurs="0">
					<xs:element name="subject" type="xs:string" minOccurs="0">
						<xs:annotation>
							<xs:appinfo>
								<xdat:field display="true"/>
							</xs:appinfo>
						</xs:annotation>
					</xs:element>
					<xs:element name="qcSession" minOccurs="0" >
						<xs:complexType>
							<xs:sequence minOccurs="0">
								<xs:element name="imgData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="date" type="xs:date" use="required"/>
										<xs:attribute name="time" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="tisData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence minOccurs="0">
											<xs:element name="tissue" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="imageFile" type="xs:string"/>
													<xs:attribute name="imageType" type="xs:string"/>
													<xs:attribute name="gm" type="xs:float"/>
													<xs:attribute name="wm" type="xs:float"/>
													<xs:attribute name="csf" type="xs:float"/>
													<xs:attribute name="gmThresh" type="xs:float"/>
													<xs:attribute name="wmThresh" type="xs:float"/>
													<xs:attribute name="csfThresh" type="xs:float"/>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="filedate" type="xs:date" use="required"/>
										<xs:attribute name="filetime" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="qcImage" type="xs:string" use="optional"/>
							<xs:attribute name="quality" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="username" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="date" type="xs:date" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="time" type="xs:time" use="required"/>
							<xs:attribute name="comments" use="optional" type="xs:string"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="NormCat12PETPVCData">
		<xs:complexContent>
			<xs:extension base="xnat:mrAssessorData">
				<xs:annotation>
					<xs:documentation>CAT12 Normalization of PETPVC QA Report</xs:documentation>
				</xs:annotation>
				<xs:sequence minOccurs="0">
					<xs:element name="subject" type="xs:string" minOccurs="0">
						<xs:annotation>
							<xs:appinfo>
								<xdat:field display="true"/>
							</xs:appinfo>
						</xs:annotation>
					</xs:element>
					<xs:element name="qcSession" minOccurs="0" >
						<xs:complexType>
							<xs:sequence minOccurs="0">
								<xs:element name="imgData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="date" type="xs:date" use="required"/>
										<xs:attribute name="time" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="tisData" minOccurs="0" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence minOccurs="0">
											<xs:element name="tissue" minOccurs="0" maxOccurs="unbounded">
												<xs:complexType>
													<xs:attribute name="imageFile" type="xs:string"/>
													<xs:attribute name="imageType" type="xs:string"/>
													<xs:attribute name="gm" type="xs:float"/>
													<xs:attribute name="wm" type="xs:float"/>
													<xs:attribute name="csf" type="xs:float"/>
													<xs:attribute name="rv" type="xs:float"/>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="file" type="xs:string" use="required"/>
										<xs:attribute name="filedate" type="xs:date" use="required"/>
										<xs:attribute name="filetime" type="xs:time" use="required"/>
										<xs:attribute name="quality" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="qcImage" type="xs:string" use="optional"/>
							<xs:attribute name="quality" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="username" type="xs:string" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="date" type="xs:date" use="required">
								<xs:annotation>
									<xs:appinfo>
										<xdat:field display="true"/>
									</xs:appinfo>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="time" type="xs:time" use="required"/>
							<xs:attribute name="comments" use="optional" type="xs:string"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
		
</xs:schema>